sudo: required
language: cpp
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

env:
  global:
    - CMAKE_VERSION_MAJOR=v3.11
    - CMAKE_VERSION=3.11.0
    - NINJA_VERSION=v1.7.2
    - LLVM_VERSION=6.0.0
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
    - export PATH=$HOME/usr/bin:$PATH
    - export LD_LIBRARY_PATH=$HOME/usr/lib:$LD_LIBRARY_PATH

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install lit

install:
  - cd $HOME/build
  # Install LLVM/Clang 6.0
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/usr
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/usr --strip-components 1
  # Obtain and install cmake
  - wget https://cmake.org/files/$CMAKE_VERSION_MAJOR/cmake-$CMAKE_VERSION-Linux-x86_64.sh
  - chmod +x cmake-$CMAKE_VERSION-Linux-x86_64.sh
  - ./cmake-$CMAKE_VERSION-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir
  # Obtain and install ninja
  - curl -L https://github.com/ninja-build/ninja/releases/download/$NINJA_VERSION/ninja-linux.zip -o ninja-linux.zip
  - unzip ninja-linux.zip -d $HOME/usr/bin
  # Install testing tools
  - git clone --recursive https://github.com/PRUNERS/TestingTools.git
  - cd TestingTools
  - mkdir build && cd build
  - cmake -G Ninja -D CMAKE_CXX_COMPILER=clang++ -D CMAKE_INSTALL_PREFIX:PATH=$HOME/usr -DCMAKE_CXX_FLAGS="-fno-rtti" ..
  - ninja && ninja install

script:
  - cd $HOME/build/PRUNERS
  - rm -rf openmp
  - git clone https://github.com/llvm-mirror/openmp.git
  - export OPENMP_INSTALL=$HOME/usr
  - cd openmp
  - mkdir build && cd build
  - cmake -G Ninja -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX:PATH=$OPENMP_INSTALL ..
  - ninja -j4 -l4
  - ninja install
  - export SWORD_INSTALL=$HOME/usr
  - cd $HOME/build/PRUNERS/sword
  - rm -rf build
  - mkdir -p build && cd build
  - cmake -G Ninja -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ -D CMAKE_INSTALL_PREFIX:PATH=${SWORD_INSTALL} -D OMP_PREFIX:PATH=$OPENMP_INSTALL -D SWORD_LLVM_LIT_EXECUTABLE=$HOME/usr/bin/llvm-lit -D SWORD_LLVM_TOOLS_DIR=$HOME/usr/bin ..
  - ninja -j4 -l4
  - ninja install
  - ninja check-libsword

notifications:
  email: false
  slack:
    rooms:
      - pruners:aXHVdiVFtqtMfzNW4IutZNDW
    on_success: always
    on_failure: always
